spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      leak-detection-threshold: 20000
      data-source-properties:
        prepareThreshold: 0
        useServerPrepStmts: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false